[package]
name = "mcpixel"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["recommended", "schematic"]
recommended = ["rayon", "default-formats"]
wasm = ["mc_schem/wasm"]

clap = ["dep:clap"]
default-formats = ["image/default-formats"]
rayon = ["image/rayon"]
schematic = ["dep:mc_schem"]

[dependencies]
clap = { workspace = true, features = ["derive"], optional = true }
exoquant.workspace = true
image.workspace = true
kiddo.workspace = true
thiserror.workspace = true
prost.workspace = true
palette.workspace = true
mc_schem = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen.workspace = true
tsify.workspace = true
wasm-bindgen.workspace = true

[build-dependencies]
prost-build.workspace = true
