[workspace]
resolver = "3"
default-members = ["mcpixel-cli"]
members = ["mcpixel", "mcpixel-cli"]

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.6.0", default-features = false }
directories = "6.0.0"
exoquant = "0.2.0"
image = { version = "0.25.10", default-features = false }
kiddo = "5.3.0"
mcpixel = { path = "mcpixel" }
miette = "7.6.0"
palette = "0.7.6"
prost = "0.14.3"
prost-build = "0.14.3"
thiserror = "2.0.18"
ureq = "3.3.0"
hex = "0.4.3"
md5 = "0.8.0"
serde = "1.0.228"
console_error_panic_hook = "0.1.7"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.118"
mc_schem = { git = "https://github.com/isitreallyalive/mc_schem" }
tsify = "0.5.6"
