syntax = "proto3";

package block;

// todo: investigate scaling up floats to fit in sint32

message PlacedBlock {
  uint32 i = 1; // index into the dictionary
  bool top = 2;
}

message Texture {
  PlacedBlock base = 1;
  optional PlacedBlock overlay = 2;
  Lab average = 3;
  float smoothness = 4;
  repeated Lab colours = 5;
  repeated float weights = 6 [packed = true];
}

message Lab {
  float l = 1;
  float a = 2;
  float b = 3;
}

message Version {
  repeated string ids = 1; // dictionary
  repeated Texture textures = 2;
}